import {
  deepPurple,
  green,
  lime,
  orange,
  amber,
  indigo,
} from '@material-ui/core/colors';

export default {
  1: {
    primaryColor: '#bca070',
    link: '/rera/buyer-form',
    src: '/static/img/ARRA.png',
    entity: 'RERA',
    actor: 'Buyer',
    nextMsg: 'RERA - Seller Ownership Transfer Approval',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  2: {
    primaryColor: '#bca070',
    link: '/rera/seller-form',
    src: '/static/img/ARRA.png',
    entity: 'RERA',
    actor: 'Seller',
    nextMsg: 'RERA - Admin Ownership Transfer Approval',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  3: {
    primaryColor: '#bca070',
    link: '/rera/admin-form',
    src: '/static/img/ARRA.png',
    entity: 'RERA',
    actor: 'RERA Admin',
    nextMsg: 'MPD - Buyer No Objection Certificate Request',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  4: {
    primaryColor: '#3B8AB3',
    link: '/mpd/buyer-verification-form',
    src: '/static/img/MPD.png',
    entity: 'MPD',
    actor: 'Buyer',
    nextMsg: 'MPD - Admin No Objection Certificate Approval',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  5: {
    primaryColor: '#3B8AB3',
    link: '/mpd/admin-form',
    src: '/static/img/MPD.png',
    entity: 'MPD',
    actor: 'MPD Admin',
    nextMsg: 'FEWA - Buyer No Objection Certificate Request',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  6: {
    primaryColor: '#ececec',
    link: '/fewa/buyer-noc-form',
    src: '/static/img/FEWA.png',
    entity: 'FEWA',
    actor: 'Buyer',
    nextMsg: 'FEWA - Admin No Objection Certificate Approval',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  7: {
    primaryColor: '#ececec',
    link: '/fewa/admin-form',
    src: '/static/img/FEWA.png',
    entity: 'FEWA',
    actor: 'FEWA Admin',
    nextMsg: 'MOJ - Seller No Objection Certificate Request',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  8: {
    primaryColor: '#b08a27',
    link: '/moj/seller-noc-form',
    src: '/static/img/MOJ.png',
    entity: 'MOJ',
    actor: 'Seller',
    nextMsg: 'MOJ - Admin No Objection Certificate Approval',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  9: {
    primaryColor: '#b08a27',
    link: '/moj/admin-form',
    src: '/static/img/MOJ.png',
    entity: 'MOJ',
    actor: 'MOJ Admin',
    nextMsg: 'ABD - Buyer Mortgage Request',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  10: {
    primaryColor: '#bd2138',
    link: '/abd/buyer-request-form',
    src: '/static/img/ABD.png',
    entity: 'ABD',
    actor: 'Buyer',
    nextMsg: 'ABD - Admin Mortgage Approval',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  11: {
    primaryColor: '#bd2138',
    link: '/abd/admin-form',
    src: '/static/img/ABD.png',
    entity: 'ABD',
    actor: 'ABD Admin',
    nextMsg: 'ENBD - Admin Mortgage Approval',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  12: {
    primaryColor: '#18297c',
    link: '/enbd/admin-form',
    src: '/static/img/ENBD.png',
    entity: 'ENBD',
    actor: 'ENBD Admin',
    nextMsg: 'RERA - Buyer Title Deed Request',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  13: {
    primaryColor: '#bca070',
    link: '/rera/buyer-td-form',
    src: '/static/img/ARRA.png',
    entity: 'RERA',
    actor: 'Buyer',
    nextMsg: 'RERA - Admin Title Deed Approval',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  14: {
    primaryColor: '#bca070',
    link: '/rera/admin-td-form',
    src: '/static/img/ARRA.png',
    entity: 'RERA',
    actor: 'RERA Admin',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  15: {
    primaryColor: '#ececec',
    link: '/fewa/buyer-form',
    src: '/static/img/FEWA.png',
    entity: 'FEWA',
    actor: 'FEWA Admin',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
  16: {
    primaryColor: '#ececec',
    link: '/fewa/admin-td-form',
    src: '/static/img/FEWA.png',
    entity: 'FEWA',
    actor: 'FEWA Admin',
    actorID: '785021039213',
    actorPassword: 'randomPassword',
  },
};
