import {
  deepPurple,
  green,
  lime,
  orange,
  amber,
  indigo,
} from '@material-ui/core/colors';
import React from 'react';


export default {
  1: {
    primaryColor: '#bca070',
    link: '/rera/buyer-form',
    src: '/static/img/ARRA.png',
    entity: 'ARRA',
    actor: 'Buyer',
    nextMsg: [" Your Ownership Transfer request has been submitted."," The seller of the property has been notified of your request."],
    loginMsg:[],
    scenarioMsg:["Please provide the details of the property you wish to buy and the seller information."],
    actorID: '784199346973961',
    actorPassword: 'randomPassword',
  },
  2: {
    primaryColor: '#bca070',
    link: '/rera/seller-form',
    src: '/static/img/ARRA.png',
    entity: 'ARRA',
    actor: 'Seller',
    nextMsg: [" You approved the Ownership Transfer of the property."," Your approval has been sent to Ajman Real estate Regulatory Authority for its verification."],
    loginMsg:[],
    scenarioMsg:[" By approving this request, you as the owner of this property confirm  the Ownership Transfer of this property. "],
    actorID: '784198526973565',
    actorPassword: 'randomPassword',
  },
  3: {
    primaryColor: '#bca070',
    link: '/rera/admin-form',
    src: '/static/img/ARRA.png',
    entity: 'ARRA',
    actor: 'ARRA Admin',
    nextMsg: [" Ajman Real estate Regulatory Authority has successfully approved the request of the Ownership Transfer."," The approval has been sent to buyer and seller through SMS and emails."],
    loginMsg:[],
    scenarioMsg:[" By approving this request, you as the representative of ARRA verify and confirm the request of this Ownership Transfer."],
    actorID: '784197626973565',
    actorPassword: 'randomPassword',
  },
  4: {
    primaryColor: '#3B8AB3',
    link: '/mpd/buyer-verification-form',
    src: '/static/img/MPD.png',
    entity: 'MPD',
    actor: 'Buyer',
    nextMsg: [" Your No Objection Certificate (NOC) request has been submitted to Ajman MPD."],
    loginMsg:[],
    scenarioMsg:["Buyer to upload the Ownership Transfer document."],
    actorID: '784199346973961',
    actorPassword: 'randomPassword',
  },
  5: {
    primaryColor: '#3B8AB3',
    link: '/mpd/admin-form',
    src: '/static/img/MPD.png',
    entity: 'MPD',
    actor: 'MPD Admin',
    nextMsg: [" Ajman MPD has successfully verified the Ownership Transfer document."," Ajman MPD - NOC has been issued and sent to buyer through SMS and email."],
    loginMsg:[],
    scenarioMsg: [" By approving this, you as the representative of Ajman MPD  verify the Ownership Transfer document  and  issue an Ajman MPD NOC."," Please ensure all necessary checks and internal procedures have been done before this approval."],
    actorID: '784197311267456',
    actorPassword: 'randomPassword',
  },
  6: {
    primaryColor: '#ececec',
    link: '/fewa/buyer-noc-form',
    src: '/static/img/FEWA.png',
    entity: 'FEWA',
    actor: 'Buyer',
    nextMsg: [" Your NOC request has been submitted to FEWA."],
    loginMsg:[],
    scenarioMsg: [" Buyer to upload the Ownership Transfer document and  Ajman MPD NOC."],
    actorID: '784199346973961',
    actorPassword: 'randomPassword',
  },
  7: {
    primaryColor: '#ececec',
    link: '/fewa/admin-form',
    src: '/static/img/FEWA.png',
    entity: 'FEWA',
    actor: 'FEWA Admin',
    nextMsg: [" FEWA has successfully verified the Ownership Transfer document and Ajman MPD NOC."," FEWA - NOC has been issued and sent to buyer through SMS and email."],
    loginMsg:[],
    scenarioMsg: [" By approving this, you as the representative of the FEWA  verify the Ownership Transfer document and Ajman MPD NOC, and issue a FEWA NOC."," Please ensure all necessary checks and internal procedures have been done before this approval."],
    actorID: '784199346973961',
    actorPassword: 'randomPassword',
  },
  8: {
    primaryColor: '#b08a27',
    link: '/moj/seller-noc-form',
    src: '/static/img/MOJ.png',
    entity: 'MOJ',
    actor: 'Seller',
    nextMsg: [" Your NOC request has been submitted to MOJ."],
    loginMsg:[],
    scenarioMsg: [" Seller to upload the Ownership Transfer document and  the original Title Deed."],
    actorID: '784198526973565',
    actorPassword: 'randomPassword',
  },
  9: {
    primaryColor: '#b08a27',
    link: '/moj/admin-form',
    src: '/static/img/MOJ.png',
    entity: 'MOJ',
    actor: 'MOJ Admin',
    nextMsg: [" MOJ has successfully verified the Ownership Transfer document and the Title Deed."," MOJ - NOC has been issued and sent to seller and buyer through SMS and email."],
    loginMsg:[],
    scenarioMsg: [" By approving this, you as the representative of the MOJ verify the Ownership Transfer document and the Title Deed, and issue an MOJ NOC."," Please ensure all necessary checks and internal procedures have been done before this approval."],
    actorID: '784197499786531',
    actorPassword: 'randomPassword',
  },
  10: {
    primaryColor: '#bd2138',
    link: '/abd/buyer-request-form',
    src: '/static/img/ABD.png',
    entity: 'ABD',
    actor: 'Buyer',
    nextMsg: [" Your Mortgage request has been submitted to Ajman Bank."],
    loginMsg:[],
    scenarioMsg: [" Buyer to upload the Ownership Transfer document, Ajman MPD NOC, FEWA NOC and MOJ NOC."],
    actorID: '784199346973961',
    actorPassword: 'randomPassword',
  },
  11: {
    primaryColor: '#bd2138',
    link: '/abd/admin-form',
    src: '/static/img/ABD.png',
    entity: 'ABD',
    actor: 'Ajman Bank Admin',
    nextMsg: [" Ajman Bank has successfully verified the Ownership Transfer document, Ajman MPD NOC, FEWA NOC and MOJ NOC."," The Mortgage Approval has been issued and sent to buyer."],
    loginMsg:[],
    scenarioMsg: [" By approving this, you as the representative of Ajman Bank verify the Ownership Transfer document, Ajman MPD NOC, FEWA NOC and MOJ NOC, and issue a Mortgage Approval.", " Please ensure all necessary checks and internal procedures have been done before this approval."],
    actorID: '784199346903902',
    actorPassword: 'randomPassword',
  },
  12: {
    primaryColor: '#f8f9fa',
    link: '/enbd/admin-form',
    src: '/static/img/centralBank.png',
    entity: 'CentralBank',
    actor: 'Central Bank Admin',
    nextMsg: [" Central Bank has successfully verified the Mortgage Approval document"],
    loginMsg:[],
    scenarioMsg: [" By approving this, you as the representative of Central Bank verify the Mortgage Approval document.", " Please ensure all necessary checks and internal procedures have been done before this approval."],
    actorID: '784199236734452',
    actorPassword: 'randomPassword',
  },
  13: {
    primaryColor: '#bca070',
    link: '/rera/buyer-td-form',
    src: '/static/img/ARRA.png',
    entity: 'ARRA',
    actor: 'Buyer',
    nextMsg: [" Your Title Deed request has been submitted to ARRA."],
    loginMsg:[],
    scenarioMsg: [" Buyer to upload the Ownership Transfer document, Ajman MPD NOC, FEWA NOC, MOJ NOC, the original Title Deed and Mortgage Approval."],
    actorID: '784199346973961',
    actorPassword: 'randomPassword',
  },
  14: {
    primaryColor: '#bca070',
    link: '/rera/admin-td-form',
    src: '/static/img/ARRA.png',
    entity: 'ARRA',
    actor: 'ARRA Admin',
    nextMsg: [" ARRA has successfully verified the Ownership Transfer document, Ajman MPD NOC, FEWA NOC and MOJ NOC, the original Title Deed and Mortgage Approval.", "The Title Deed has been issued and sent to buyer."],
    loginMsg:[],
    scenarioMsg: [" By approving this, you as the representative of ARRA  verify the Ownership Transfer document, Ajman MPD NOC, FEWA NOC, MOJ NOC, the original Title Deed and Mortgage Approval and issue a new Title Deed.", " Please ensure all necessary checks and internal procedures have been done before this approval."],
    actorID: '784197626973565',
    actorPassword: 'randomPassword',
  }
};